apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: muhammad0320/account
          env:
            - name: MONGO_URI
              value: "mongodb://account-mongo-srv:27017/account"
            - name: JWT_EXPIRES_IN
              value: "24"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: account-srv
spec:
  selector:
    app: account
  ports:
    - name: account
      protocol: TCP
      port: 3000
      targetPort: 3000
